export default [
  { heading: 'الإدارة' },
  {
    title: 'المستخدمون',
    icon: { icon: 'mdi-account-group-outline' },
    to: 'apps-users',
    action: 'read',
    subject: 'users',
  },
  {
    title: 'النباتات',
    icon: { icon: 'mdi-tree-outline' },
    to: 'apps-plants',
    badgeContent: 'جديد',
    badgeClass: 'bg-error',
    action: 'read',
    subject: 'plants',
  },
  {
    title: 'خريطة النباتات',
    icon: { icon: 'mdi-map-outline' },
    to: 'apps-plants-map',
    action: 'read',
    subject: 'plants',
  },
  {
    title: 'الإبلاغات',
    icon: { icon: 'mdi-alert-octagon-outline' },
    to: 'apps-reports',
    badgeContent: 'مهم',
    badgeClass: 'bg-warning',
    action: 'read',
    subject: 'reports',
  },
  {
    title: 'البنرات',
    icon: { icon: 'mdi-image-multiple-outline' },
    to: 'apps-banners',
    action: 'read',
    subject: 'banners',
  },
  {
    title: 'إعلانات الشاشة',
    icon: { icon: 'mdi-dock-top' },
    to: 'apps-screen-ads',
    action: 'read',
    subject: 'screen_ads',
  },
  {
    title: 'المحافظات',
    icon: { icon: 'mdi-map-marker-outline' },
    to: 'apps-governorates',
    action: 'read',
    subject: 'governorates',
  },
  { heading: 'الأدوار والصلاحيات' },
  {
    title: 'الأدوار',
    icon: { icon: 'mdi-shield-account-outline' },
    to: 'apps-roles',
    action: 'read',
    subject: 'roles',
  },
  {
    title: 'حملات التشجير',
    icon: { icon: 'mdi-flag-variant-outline' },
    to: 'apps-campaigns',
    action: 'read',
    subject: 'campaigns',
  },
  {
    title: 'ألقاب المستخدمين',
    icon: { icon: 'mdi-medal-outline' },
    to: 'apps-user-levels',
    action: 'read',
    subject: 'user_levels',
  },
  {
    title: 'الصلاحيات',
    icon: { icon: 'mdi-shield-key-outline' },
    to: 'apps-permissions',
    action: 'read',
    subject: 'roles', // Permissions usually falls under roles
  },
  { heading: 'الإعدادات' },
  {
    title: 'إرسال إشعار',
    icon: { icon: 'mdi-bell-outline' },
    to: 'apps-notifications',
    action: 'read',
    subject: 'notifications',
  },
  {
    title: 'إصدارات التطبيق',
    icon: { icon: 'mdi-cellphone-arrow-down' },
    to: 'apps-app-versions',
    action: 'read',
    subject: 'app_versions',
  },
  {
    title: 'الإعدادات العامة',
    icon: { icon: 'mdi-cog-outline' },
    to: 'apps-settings',
    action: 'read',
    subject: 'settings',
  },
]
